#!/bin/bash
# NOTE: Don't run this script with PRs, wait until it's merged to develop, this prevents complicated merge conflicts between pending PRS
bash ./scripts/build

docker create --name express-async-handler express-async-handler:local /bin/sh

docker cp express-async-handler:/app/package.json ./package.json
docker cp express-async-handler:/app/package-lock.json ./package-lock.json
docker rm -fv express-async-handler
echo "complete"
